import type { User, Collection, Report } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@residuos.com",
    name: "Administrador Sistema",
    role: "admin",
    phone: "+1234567890",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    email: "juan.cliente@email.com",
    name: "Juan Pérez",
    role: "cliente",
    phone: "+1234567891",
    address: "Calle 123, Ciudad",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "3",
    email: "maria.cliente@email.com",
    name: "María González",
    role: "cliente",
    phone: "+1234567892",
    address: "Avenida 456, Ciudad",
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "4",
    email: "empresa@ecolimpia.com",
    name: "Carlos Rodríguez",
    role: "empresa_recolectora",
    phone: "+1234567893",
    company: "EcoLimpia S.A.",
    createdAt: new Date("2024-01-10"),
  },
]

export const mockCollections: Collection[] = [
  {
    id: "1",
    clientId: "2",
    companyId: "4",
    type: "organicos",
    scheduledDate: new Date("2024-12-20"),
    scheduledTime: "09:00",
    address: "Calle 123, Ciudad",
    quantity: 15,
    status: "completada",
    notes: "Recolección regular semanal",
    completedAt: new Date("2024-12-20T09:30:00"),
    createdAt: new Date("2024-12-15"),
  },
  {
    id: "2",
    clientId: "3",
    companyId: "4",
    type: "reciclables",
    scheduledDate: new Date("2024-12-22"),
    scheduledTime: "14:00",
    address: "Avenida 456, Ciudad",
    quantity: 8,
    status: "programada",
    notes: "Incluye cartón y plástico",
    createdAt: new Date("2024-12-18"),
  },
  {
    id: "3",
    clientId: "2",
    type: "general",
    scheduledDate: new Date("2024-12-25"),
    scheduledTime: "10:00",
    address: "Calle 123, Ciudad",
    quantity: 20,
    status: "programada",
    createdAt: new Date("2024-12-19"),
  },
]

export const mockReports: Report[] = [
  {
    id: "1",
    userId: "2",
    collectionId: "1",
    date: new Date("2024-12-20"),
    location: "Calle 123, Ciudad",
    quantity: 15,
    wasteType: "organicos",
    status: "completada",
    notes: "Recolección exitosa",
  },
  {
    id: "2",
    userId: "3",
    collectionId: "2",
    date: new Date("2024-12-22"),
    location: "Avenida 456, Ciudad",
    quantity: 8,
    wasteType: "reciclables",
    status: "programada",
  },
]
